### ISSUE TITLE
Wave 5 error with the less than or equal to character

### ISSUE THREAD

**Issue by bjsmith** [mnoetel/READI-SCRUB#30]
I get the following error when trying to import the wave 5 version of `latest_open_science_data.RDS`

```
Warning messages:
1: In readRDS(path) :
  input string '≤ 5,000 people' cannot be translated to UTF-8, is it valid in 'US-ASCII'?
```

It is related to the inhabitants column.

I edited the inhab_labels variable on lines 1321 to 1325 of the cleaning code script to avoid that character, like:

```
inhab_labels <- "5,000 people or less  (1) 
o	5,001 - 20,000  (2) 
o	20,001 - 100,000  (3) 
o	100,001 - 500,000  (4) 
o	500,000 people or more  (5)"
```

But I don't know if this will fix the problem and it might even break it, if the original qualtrics file has the less than character and if `inhab_labels` needs to match it.

**Comment by mnoetel** [comment]
Great pickup Ben, thank you. Think I’ve fixed it.
